### ISSUE TITLE
在Koishi控制台下无法启用该插件

### ISSUE THREAD

**Issue by cacan180** [MirrorCY/sd-extra#2]
如题
log下显示
2022-11-20 12:35:22 [I] app apply plugin sd-extra
2022-11-20 12:35:25 [I] app apply plugin sd-extra
2022-11-20 12:35:42 [I] app apply plugin sd-extra

插件配置中为灰色
![2](https://user-images.githubusercontent.com/48651501/202886474-f20f6887-22a0-410e-87c2-d86f51155295.png)

**Comment by MirrorCY** [comment]
可以提供更详细的相关日志或者最小复现方法吗，目前的信息无法定位问题

**Comment by MirrorCY** [comment]
已在全新环境复现此问题，将尽快修复

**Comment by MirrorCY** [comment]
已定位问题并更新 0.0.6，请测试新版本是否解决了这个问题

**Comment by cacan180** [comment]
您好 问题已经解决， 谢谢

**Comment by MirrorCY** [comment]
感谢反馈，使用愉快~
