### ISSUE TITLE
关于sd-extra无法在discord中工作的问题

### ISSUE THREAD

**Issue by cacan180** [MirrorCY/sd-extra#3]
在discord中提交 extra后，会返回如下错误↓
![image](https://user-images.githubusercontent.com/48651501/202953871-32db3889-d7de-4ef2-ba70-dd25690f959b.png)

查看koishi后台日志，报错如下↓
![image](https://user-images.githubusercontent.com/48651501/202953952-94fe53fc-a54d-485e-aefb-9f208195ec40.png)

查询超时连接ip地址，指向的是facebook的服务器，显然这些地址是无法在中国内地访问的，使用外网环境时工作正常。

因为使用平台只有discord和qq两个环境，所以没有测试telegram的情景。
我个人判断这个应该跟adapter-discord里agent的作用范围有关系，这部分的实现好像是satori的部分，所以不知道这个issue发在这里合不合适，如果这不是您这部分代码的问题，可能需要麻烦您帮忙进行转交。

**Comment by MirrorCY** [comment]
感谢你的反馈！由于适配器返回的图像为 url，所以图像下载的部分是在插件中完成的，你可以尝试在 koishi 全局配置中设置 `request.proxyAgent` 以实现通过 agent 获取消息中的图片。
同时，此处可能还存在另一个问题，可以参考[此 issue](https://github.com/satorijs/satori/issues/39)
下载图片的实现如下，如果有更好的解决方案，例如在插件内实现独立代理，欢迎 pr！
https://github.com/MirrorCY/sd-extra/blob/main/src/index.ts#L64

**Comment by cacan180** [comment]
目前已在全局设置中挂代理，discord运行已正常，感谢指导。
