### ISSUE TITLE
放大插件报错：发生未知错误 (500)。

### ISSUE THREAD

**Issue by Neptune1990** [MirrorCY/sd-extra#5]
放大插件报错：发生未知错误 (500)。
适配器为red

System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700

Binaries:
    Node: 20.3.1
    Yarn: 4.0.1

Koishi:
    Core: 4.16.7
    Console: 5.26.6
    Koishi Desktop: 1.0.0

**Comment by Neptune1990** [comment]
![image](https://github.com/MirrorCY/sd-extra/assets/107494041/52cdea95-0154-4078-adb2-25312f017140)
设置已正确配置

**Comment by MirrorCY** [comment]
500 看起来是服务器那边的问题，我晚点看看，已经挺久没测试这个插件了

**Comment by Neptune1990** [comment]
onebot适配器倒是正常的，不过之前koishi大更新之后发不出图了。
