### ISSUE TITLE
最新版本koishi使用返回不支持的文件格式。

### ISSUE THREAD

**Issue by Neptune1990** [MirrorCY/sd-extra#7]
最新版本koishi使用返回不支持的文件格式。
日志无报错
System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700

Binaries:
    Node: 20.3.1
    Yarn: 4.0.1

Koishi:
    Core: 4.17.1
    Console: 5.26.6
    Koishi Desktop: 1.0.0

**Comment by MirrorCY** [comment]
周一看看

**Comment by Neptune1990** [comment]
探头

**Comment by LingChen-tsjmdlc** [comment]
+1

**Comment by MirrorCY** [comment]
should fix in f04376b3c0abe57309ae70a5cc35f127fa67ee22
